// default package
// Generated Mar 26, 2013 11:20:30 PM by Hibernate Tools 3.4.0.CR1


import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Home object for domain model class Cardreposts.
 * @see .Cardreposts
 * @author Hibernate Tools
 */
@Stateless
public class CardrepostsHome {

    private static final Log log = LogFactory.getLog(CardrepostsHome.class);

    @PersistenceContext private EntityManager entityManager;
    
    public void persist(Cardreposts transientInstance) {
        log.debug("persisting Cardreposts instance");
        try {
            entityManager.persist(transientInstance);
            log.debug("persist successful");
        }
        catch (RuntimeException re) {
            log.error("persist failed", re);
            throw re;
        }
    }
    
    public void remove(Cardreposts persistentInstance) {
        log.debug("removing Cardreposts instance");
        try {
            entityManager.remove(persistentInstance);
            log.debug("remove successful");
        }
        catch (RuntimeException re) {
            log.error("remove failed", re);
            throw re;
        }
    }
    
    public Cardreposts merge(Cardreposts detachedInstance) {
        log.debug("merging Cardreposts instance");
        try {
            Cardreposts result = entityManager.merge(detachedInstance);
            log.debug("merge successful");
            return result;
        }
        catch (RuntimeException re) {
            log.error("merge failed", re);
            throw re;
        }
    }
    
    public Cardreposts findById( CardrepostsId id) {
        log.debug("getting Cardreposts instance with id: " + id);
        try {
            Cardreposts instance = entityManager.find(Cardreposts.class, id);
            log.debug("get successful");
            return instance;
        }
        catch (RuntimeException re) {
            log.error("get failed", re);
            throw re;
        }
    }
}

